# General
server:
  port: 8001

spring:
  jpa:
    database-platform: org.hibernate.dialect.OracleDialect
    hibernate.ddl-auto: create
    show-sql: true
    properties:
      hibernate.format_sql: true
  datasource:
    url: jdbc:oracle:thin:@localhost:11521:XE
    username: user
    password: password
    driver-class-name: oracle.jdbc.OracleDriver

# Logging
logging:
  level:
    com.test.action: debug
    org.hibernate.SQL: info
    org.springframework: info
